# Generated by Django 5.0.6 on 2024-06-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningPlatform', '0002_alter_course_options_alter_enrollment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='other', max_length=100, verbose_name='Course Category'),
        ),
        migrations.AddField(
            model_name='course',
            name='estimated_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estimated Time'),
        ),
        migrations.AddField(
            model_name='course',
            name='target_audience',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Target Audience'),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='Thumbnail'),
        ),
    ]
