# Generated by Django 5.0.6 on 2024-07-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningPlatform', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed_lessons',
            field=models.ManyToManyField(blank=True, related_name='completed_by', to='learningPlatform.lesson'),
        ),
    ]
